import re
from pathlib import Path

# Devanagari numerals
DEVANAGARI_MAP = str.maketrans("०१२३४५६७८९", "0123456789")

GANAS = {
    1: "Bhvadi",
    2: "Adadi",
    3: "Juhotyadi",
    4: "Divadi",
    5: "Svadi",
    6: "Tudadi",
    7: "Rudhadi",
    8: "Tanadi",
    9: "Kryadi",
    10: "Curadi"
}

def clean_id(text_id):
    """Convert १.१ to 1.1"""
    return text_id.translate(DEVANAGARI_MAP)

def scaffold_roots():
    data_path = Path("panini_nlp/data/Dhatupatha.txt")
    output_dir = Path("panini_nlp/roots")
    output_dir.mkdir(parents=True, exist_ok=True)

    if not data_path.exists():
        print(f"Error: {data_path} not found.")
        return

    content = data_path.read_text(encoding="utf-8")
    lines = content.splitlines()

    # Buffer for each Gana
    ganas_code = {i: [] for i in range(1, 11)}
    
    current_gana = 1 # Default

    # Regex for standard root line: १.१ भू सत्तायाम् । ...
    root_pattern = re.compile(r"^([\d\.]+)\s+([^\s]+)\s+([^।]+)(?:।|$)")

    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Check for Gana header? We rely on the ID prefix mostly: 1.x, 2.x
        # But let's rely on the numbering
        
        match = root_pattern.match(line)
        if match:
            raw_id, root, meaning = match.groups()
            cleaned_id = clean_id(raw_id)
            
            try:
                major_gana = int(cleaned_id.split('.')[0])
                if major_gana in ganas_code:
                    current_gana = major_gana
            except ValueError:
                pass
            
            # Generate code
            safe_root = root.replace('"', '\\"')
            safe_meaning = meaning.strip().replace('"', '\\"')
            gana_name = GANAS.get(current_gana, f"Gana_{current_gana}")
            func_name = f"root_{cleaned_id.replace('.', '_')}"

            code_block = f"""
@registry.register("{cleaned_id}", root="{safe_root}", meaning="{safe_meaning}", gana="{gana_name}")
def {func_name}():
    \"\"\"
    {cleaned_id} {root} {meaning}
    \"\"\"
    return "{safe_root}"
"""
            ganas_code[current_gana].append(code_block)

    # Write files
    for g_num, codes in ganas_code.items():
        if not codes:
            continue
            
        gana_name = GANAS.get(g_num, f"gana_{g_num}").lower()
        filename = output_dir / f"gana_{g_num}_{gana_name}.py"
        
        file_content = [
            f"# Auto-generated by scripts/scaffold_roots.py for Gana {g_num}",
            "from . import registry",
            ""
        ] + codes
        
        filename.write_text("\n".join(file_content), encoding="utf-8")
        print(f"Generated {filename} with {len(codes)} roots.")

if __name__ == "__main__":
    scaffold_roots()
