import re
from pathlib import Path

# Mapping Devanagari numerals to standard digits for filename/ID generation
DEVANAGARI_MAP = str.maketrans("०१२३४५६७८९", "0123456789")

def clean_rule_id(text_id):
    """Convert १.१.१ to 1.1.1"""
    return text_id.translate(DEVANAGARI_MAP)

def scaffold_rules():
    data_path = Path("panini_nlp/data/Ashtadhyayi.txt")
    output_dir = Path("panini_nlp/rules")
    output_dir.mkdir(parents=True, exist_ok=True)

    if not data_path.exists():
        print(f"Error: {data_path} not found.")
        return

    content = data_path.read_text(encoding="utf-8")
    lines = content.splitlines()

    # Buffer for each Adhyaya
    # structure: { adhyaya_num: [list of code strings] }
    adhyayas = {}
    
    current_adhyaya = 0

    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Check for Adhyaya header
        # ॥ अध्याय १ ॥
        if "अध्याय" in line:
            match = re.search(r"अध्याय\s+([१-९])", line)
            if match:
                current_adhyaya = int(match.group(1).translate(DEVANAGARI_MAP))
                if current_adhyaya not in adhyayas:
                    adhyayas[current_adhyaya] = []
            continue

        # Parse rule line: १.१.१ वृद्धिरादैच् ।
        # Regex: (ID) space (Rule Text)
        parts = line.split(" ", 1)
        if len(parts) < 2:
            continue
            
        raw_id, raw_text = parts[0], parts[1]
        
        # Validate ID format (x.x.x)
        clean_id = clean_rule_id(raw_id)
        if not re.match(r"^\d+\.\d+\.\d+$", clean_id):
            continue

        # Determine Adhyaya from ID if header missed (fallback)
        adh_num = int(clean_id.split(".")[0])
        if adh_num not in adhyayas:
            adhyayas[adh_num] = []

        # Generate Python code
        # Function name derived from ID to valid identifier
        func_name = f"rule_{clean_id.replace('.', '_')}"
        
        # Escape quotes in text
        safe_text = raw_text.replace('"', '\\"')
        
        code_block = f"""
@registry.register("{clean_id}", text="{safe_text}")
def {func_name}(ctx=None):
    \"\"\"
    {clean_id}: {raw_text}
    \"\"\"
    pass
"""
        adhyayas[adh_num].append(code_block)

    # Write files
    for adh_num, codes in adhyayas.items():
        filename = output_dir / f"adhyaya_{adh_num}.py"
        file_content = [
            "# Auto-generated by scripts/scaffold_rules.py",
            "from . import registry",
            ""
        ] + codes
        
        filename.write_text("\n".join(file_content), encoding="utf-8")
        print(f"Generated {filename} with {len(codes)} rules.")

if __name__ == "__main__":
    scaffold_rules()
